site_name: Christian Boin, MASC+AI
site_url: https://cboin1996.github.io/life
site_dir: public

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode